export default {
  formHeader: {
    fontSize: 18,
    textAlign: 'center',
    paddingVertical: 10,
    backgroundColor: '#B4B7C0',
    borderBottomWidth: 0.1,
  },
  errorTextStyle: {
    fontSize: 20,
    alignSelf: 'center',
    color: 'red',
  },
  mainCard: {
    borderWidth: 1,
    borderRadius: 2,
    borderColor: '#d9edf7',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
    marginLeft: 5,
    marginRight: 5,
  },
  cardRow: {
    padding: 5,
    backgroundColor: '#fff',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    position: 'relative',
  },
  headerRow: {
    borderBottomWidth: 1,
    padding: 10,
    backgroundColor: '#d9edf7',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    borderColor: '#d9edf7',
    position: 'relative',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: 20,
  },
  formAddContainer: {
    paddingBottom: 20,
  },
};
