export default {
  labelInputStyle: {
    color: '#000',
    paddingRight: 5,
    paddingLeft: 5,
    flex: 2,
    borderColor: '#ebebeb',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    fontSize: 18,
  },
  labelStyle: {
    paddingLeft: 20,
    fontSize: 18,
    flex: 1,
  },
  iconInputStyle: {
    color: '#000',
    paddingRight: 5,
    paddingLeft: 5,
    flex: 1,
    borderColor: '#ccc',
    borderWidth: 1,
    borderBottomRightRadius: 4,
    borderTopRightRadius: 4,
    paddingVertical: 10,
    fontSize: 18,
    height: 40,
  },
  iconStyle: {
    paddingVertical: 10,
    backgroundColor: '#ccc',
    borderBottomLeftRadius: 4,
    borderTopLeftRadius: 4,
    paddingLeft: 20,
    height: 40,
    width: 50,
  },
  containerStyle: {
    height: 40,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
};
